# Contenido

1. Entrenamiento del modelo.
2. Monitoreo de scores
3. Monitoreo del performance

**Cargar archivos en el CoLab**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# LECTURA DE DATOS

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/MLOps_20252/Datasets/Data_CU_venta.csv')
df

,p_codmes,key_value,target,monto,ctd_prod_rccsf_m01,prom_salvig_entprinc_pp_rccsf_03m,max_usotcrrstsf06m,max_usotcrrstsf03m,prm_lintcribksf06m,lin_tcribksf03m,...,beta_saltotppe12m,prm_entrd03m,ctd_entrdm01,beta_saltotppe06m,prm_diasatrrd03m,prm_saltotrdpj03m,prm_saltotrdpj12m,dsv_diasatrrdpj12m,max_pctsalimpago12m,prm_diasatrrdpj03m
0,201912.0,2A7AA560ED5426EEBCBA5678510D53FDE5C30E3E309BC1...,0,15000.0,6,0.000,0.015,0.015,9400.000,28200.00,...,NaN,1.667,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,201912.0,7581203BF579C305ED0A62F8374CACD0925F7BA1C70DD2...,0,44800.0,1,0.000,0.000,0.000,10000.000,30000.00,...,NaN,1.333,1.0,NaN,0.0,57500.0,60500.000,0.0,NaN,0.0
2,201912.0,3B9C6C94C9274C64DFC7FE325931589B1C2B5B229600A1...,0,12200.0,7,3515.793,0.223,0.194,18500.000,55500.00,...,-67.669,4.667,5.0,-80.264,0.0,NaN,NaN,NaN,NaN,NaN
3,201912.0,8C9FB47C7499B7C65224D77D1BBB1C78F3AA2F4920EBF0...,0,21300.0,2,0.000,0.831,0.481,4900.000,14700.00,...,NaN,2.000,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,201912.0,4A68666AF9B98056E7B257CB44957A92EA587DAC9DB1A7...,0,36000.0,2,0.000,0.809,0.809,9000.000,27000.00,...,NaN,2.000,2.0,NaN,0.0,NaN,131.075,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79081,201911.0,A4E5482EFEF2807DDB7813E9528498FCF5F6B81B7C6D09...,0,10200.0,4,0.000,0.524,0.490,20475.685,57574.37,...,-95.630,3.667,3.0,NaN,0.0,NaN,NaN,NaN,0.049,NaN
79082,201911.0,D6E4A8D42587BEBF504FCB8E79EA254BB9BE96619D5CED...,0,12800.0,6,5494.263,0.487,0.020,6116.667,19000.00,...,-423.127,3.667,3.0,-1297.086,0.0,NaN,NaN,NaN,0.023,NaN
79083,201911.0,5B03358580A8D6ADA03582E7D97D50F62C674C0090F383...,0,9600.0,6,10783.380,0.401,0.401,9000.000,27000.00,...,-1975.294,5.333,5.0,-779.508,0.0,NaN,NaN,NaN,NaN,NaN
79084,201911.0,322A9C737747747C0AB31D867299634FF28FC92BBA0EA3...,0,30000.0,3,0.000,0.039,0.039,60000.000,180000.00,...,NaN,2.667,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
79085,201911.0,DB31BF387A776822E1F98913FF6AD80CB64DD112FD2460...,0,30000.0,8,2111.580,0.076,0.072,81883.957,251083.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## LIMPIEZA DE VARIABLES

### Calculo del total de NaNs

In [4]:
# df['seg_un'].isna() <-> df['seg_un'] == NaN
df['seg_un'].isna().sum()/len(df['seg_un'])*100

np.float64(1.8195382242116178)

In [5]:
def calculo_nan(df):
  for c in df.columns:
    porc_nan = df[c].isna().sum()/len(df[c])*100
    if porc_nan > 20: #umbral definido
      print(c, ' ', porc_nan)

calculo_nan(df)

dsv_saltotppe03m   61.735326100700505
beta_saltotppe12m   56.57259186202362
beta_saltotppe06m   62.9403434236148
prm_saltotrdpj03m   96.15861214374225
prm_saltotrdpj12m   94.28596717497409
dsv_diasatrrdpj12m   94.1266469413044
max_pctsalimpago12m   85.88372151834712
prm_diasatrrdpj03m   96.1611410363402

In [6]:
#TAREA
#todos las columnas de variables que tengan más de 80% de nulos que el umbral deben salir del dataset y de todo el proceso que sigue.

In [7]:
df.flg_saltothip12m=df.flg_saltothip12m.fillna(0)
df.flg_saltotppe12m=df.flg_saltotppe12m.fillna(0)
df.prm_pctsaltototrent12m=df.prm_pctsaltototrent12m.fillna(0)
df.prm_pctsaltotcaja12m=df.prm_pctsaltotcaja12m.fillna(0)
df.ant_saltot24m=df.ant_saltot24m.fillna(0)
df.ant_saltot12m=df.ant_saltot12m.fillna(0)
df.min_difsaltottcr12m=df.min_difsaltottcr12m.fillna(0)
df.num_incrsaldispefe06m=df.num_incrsaldispefe06m.fillna(0)
df.max_difent12m=df.max_difent12m.fillna(0)
df.num_dismsalppecons06m=df.num_dismsalppecons06m.fillna(0)
df.beta_pctusotcr12m=df.beta_pctusotcr12m.fillna(0)
df.prm_pctusosaltottcr03m=df.prm_pctusosaltottcr03m.fillna(0)
df.dsv_saltotppe03m=df.dsv_saltotppe03m.fillna(0)
df.prm_diasatrrdpn12m=df.prm_diasatrrdpn12m.fillna(0)
df.dsv_numentrdlintcr03m=df.dsv_numentrdlintcr03m.fillna(0)
df.rat_disefepnm01=df.rat_disefepnm01.fillna(0)
df.prm_diasatrrdpn06m=df.prm_diasatrrdpn06m.fillna(0)
df.pct_usotcrm01=df.pct_usotcrm01.fillna(0)
df.dsv_numentrdlintcr06m=df.dsv_numentrdlintcr06m.fillna(0)
df.beta_saltotppe12m=df.beta_saltotppe12m.fillna(0)
df.prm_entrd03m=df.prm_entrd03m.fillna(0)
df.ctd_entrdm01=df.ctd_entrdm01.fillna(0)
df.beta_saltotppe06m=df.beta_saltotppe06m.fillna(0)
df.prm_diasatrrd03m=df.prm_diasatrrd03m.fillna(0)
df.prm_saltotrdpj03m=df.prm_saltotrdpj03m.fillna(0)
df.prm_saltotrdpj12m=df.prm_saltotrdpj12m.fillna(0)
df.dsv_diasatrrdpj12m=df.dsv_diasatrrdpj12m.fillna(0)
df.max_pctsalimpago12m=df.max_pctsalimpago12m.fillna(0)
df.prm_diasatrrdpj03m=df.prm_diasatrrdpj03m.fillna(0)
df.ctd_campecstlv06m=df.ctd_campecstlv06m.fillna(0)
df.max_camptot06m=df.max_camptot06m.fillna(0)
df.min_camptot06m=df.min_camptot06m.fillna(0)
df.frc_camptot06m=df.frc_camptot06m.fillna(0)
df.rec_camptot06m=df.rec_camptot06m.fillna(0)
df.ctd_camptot06m=df.ctd_camptot06m.fillna(0)
df.prm_camptot06m=df.prm_camptot06m.fillna(0)
df.max_campecs06m=df.max_campecs06m.fillna(0)
df.min_campecs06m=df.min_campecs06m.fillna(0)
df.frc_campecs06m=df.frc_campecs06m.fillna(0)
df.rec_campecs06m=df.rec_campecs06m.fillna(0)
df.ctd_campecs06m=df.ctd_campecs06m.fillna(0)
df.prm_campecs06m=df.prm_campecs06m.fillna(0)

df.seg_un = df.seg_un.fillna(0)

In [8]:
# Imputacion por mediana
df.edad = df.edad.fillna(df.edad.median())

# Imputacion criterio experto!
df.ubigeo_buro = df.ubigeo_buro.fillna('Otros')
df.grp_riesgociiu = df.grp_riesgociiu.fillna('grupo_0')

## IMPUTACION DE VARIABLES

In [9]:
bool_s = df.seg_un.isin([0, 3])
np.where(bool_s, 0, df.seg_un)

array([1., 4., 2., ..., 4., 2., 0.])

In [10]:
np.where(df.grp_riesgociiu.isin(['grupo_2','grupo_3','grupo_9','grupo_8','grupo_1']), 'grupo_11', df.grp_riesgociiu)

array(['grupo_5', 'grupo_0', 'grupo_6', ..., 'grupo_6', 'grupo_6',
       'grupo_0'], dtype=object)

In [11]:
df["seg_un"]  = pd.Series(np.where(df.seg_un.isin([0,3]),0,df.seg_un)) # 3 -> 0
df["grp_riesgociiu"] = pd.Series(np.where(df.grp_riesgociiu.isin(['grupo_2','grupo_3','grupo_9','grupo_8','grupo_1']),'grupo_11',df.grp_riesgociiu))

In [12]:
df

,p_codmes,key_value,target,monto,ctd_prod_rccsf_m01,prom_salvig_entprinc_pp_rccsf_03m,max_usotcrrstsf06m,max_usotcrrstsf03m,prm_lintcribksf06m,lin_tcribksf03m,...,beta_saltotppe12m,prm_entrd03m,ctd_entrdm01,beta_saltotppe06m,prm_diasatrrd03m,prm_saltotrdpj03m,prm_saltotrdpj12m,dsv_diasatrrdpj12m,max_pctsalimpago12m,prm_diasatrrdpj03m
0,201912.0,2A7AA560ED5426EEBCBA5678510D53FDE5C30E3E309BC1...,0,15000.0,6,0.000,0.015,0.015,9400.000,28200.00,...,0.000,1.667,2.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0
1,201912.0,7581203BF579C305ED0A62F8374CACD0925F7BA1C70DD2...,0,44800.0,1,0.000,0.000,0.000,10000.000,30000.00,...,0.000,1.333,1.0,0.000,0.0,57500.0,60500.000,0.0,0.000,0.0
2,201912.0,3B9C6C94C9274C64DFC7FE325931589B1C2B5B229600A1...,0,12200.0,7,3515.793,0.223,0.194,18500.000,55500.00,...,-67.669,4.667,5.0,-80.264,0.0,0.0,0.000,0.0,0.000,0.0
3,201912.0,8C9FB47C7499B7C65224D77D1BBB1C78F3AA2F4920EBF0...,0,21300.0,2,0.000,0.831,0.481,4900.000,14700.00,...,0.000,2.000,2.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0
4,201912.0,4A68666AF9B98056E7B257CB44957A92EA587DAC9DB1A7...,0,36000.0,2,0.000,0.809,0.809,9000.000,27000.00,...,0.000,2.000,2.0,0.000,0.0,0.0,131.075,0.0,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79081,201911.0,A4E5482EFEF2807DDB7813E9528498FCF5F6B81B7C6D09...,0,10200.0,4,0.000,0.524,0.490,20475.685,57574.37,...,-95.630,3.667,3.0,0.000,0.0,0.0,0.000,0.0,0.049,0.0
79082,201911.0,D6E4A8D42587BEBF504FCB8E79EA254BB9BE96619D5CED...,0,12800.0,6,5494.263,0.487,0.020,6116.667,19000.00,...,-423.127,3.667,3.0,-1297.086,0.0,0.0,0.000,0.0,0.023,0.0
79083,201911.0,5B03358580A8D6ADA03582E7D97D50F62C674C0090F383...,0,9600.0,6,10783.380,0.401,0.401,9000.000,27000.00,...,-1975.294,5.333,5.0,-779.508,0.0,0.0,0.000,0.0,0.000,0.0
79084,201911.0,322A9C737747747C0AB31D867299634FF28FC92BBA0EA3...,0,30000.0,3,0.000,0.039,0.039,60000.000,180000.00,...,0.000,2.667,2.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0
79085,201911.0,DB31BF387A776822E1F98913FF6AD80CB64DD112FD2460...,0,30000.0,8,2111.580,0.076,0.072,81883.957,251083.12,...,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
p_codmes,77884.0,201910.578964,1.105269,201909.0,201910.0,201911.0,201912.00000,2.019120e+05
target,79086.0,0.037883,0.190914,0.0,0.0,0.0,0.00000,1.000000e+00
monto,77884.0,23110.271686,15716.874469,100.0,11900.0,19600.0,30000.00000,1.500000e+05
ctd_prod_rccsf_m01,79086.0,4.083175,1.841823,0.0,3.0,4.0,5.00000,1.200000e+01
prom_salvig_entprinc_pp_rccsf_03m,79086.0,6895.058693,20345.406039,0.0,0.0,0.0,4536.32925,6.922512e+05
...,...,...,...,...,...,...,...,...
prm_saltotrdpj03m,79086.0,377.657505,4193.971583,0.0,0.0,0.0,0.00000,4.930500e+05
prm_saltotrdpj12m,79086.0,765.682442,9892.370319,0.0,0.0,0.0,0.00000,1.275240e+06
dsv_diasatrrdpj12m,79086.0,0.012343,0.327749,0.0,0.0,0.0,0.00000,3.539686e+01
max_pctsalimpago12m,79086.0,0.032584,0.144843,0.0,0.0,0.0,0.00000,1.000000e+00
prm_diasatrrdpj03m,79086.0,0.003412,0.158684,0.0,0.0,0.0,0.00000,2.266700e+01

## CATEGORIAS -> NÚMERICAS

In [14]:
# MANUAL TIENE RIESGOS
# df.grp_riesgociiu = pd.Series(np.where(df.grp_riesgociiu == 'LIMA MODERNA', 1, df.grp_riesgociiu))
# df.grp_riesgociiu = pd.Series(np.where(df.grp_riesgociiu == 'REGION SUR', 2, df.grp_riesgociiu))

# Existen modelos que resulven el problema de trabajar con variables categoricas p.e. catboost

**SKLEARN ENCODING**

**Problemas de la asignación manual de de valores a las categorias**:
F 1 0
M 2 1

- a*x (sexo)+b

**ubigeo**

1.   lima centro   0
2.   lima moderna  1
3.   region norte  2
4.   region sur    3

xgboost 2.3 clase 1 y clase 2

- Puedes utilizar modelos que ya ponderan las categorias de forma directa como el catboost.

- Lo que no debes hacer es asignarlo manualmente (a dedo)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
df['ubigeo_buro'].unique() #PERMITE VER CUANTOS ELEMENTOS UNICOS HAY

array(['LIMA_MODERNA', 'REGION_SUR', 'LIMA_NORTE', 'LIMA_CALLAO',
       'LIMA_ESTE', 'REGION_CENTRO', 'REGION_NORTE', 'LIMA_CENTRO',
       'LIMA_SUR', 'REGION_ORIENTE', 'LIMA_PROVINCIA', 'Otros'],
      dtype=object)

In [17]:
ba_clase = LabelEncoder()
ba_clase.fit(df['ubigeo_buro'])
ba_clase

LabelEncoder()

In [18]:
df['ubigeo_buro'] = ba_clase.transform(df['ubigeo_buro'])

**Riesgos en la asignación de valores a categorias para la operación de modelos (MLOps)**

Si el modelo entreno con 11 categorias, y ya las pondero. Si aparece una 12ma, el preprocesamiento va a fallar, y aún de no fallar, no sabes como afectará el modelo.

**Riesgo cuando la tendencia en los datos cambia**

El modelo aprendio con valores de ingresos monetarios (sueldos) en el rango de 2K a 30K. Y un día empiezan a venir valores en rangos de 3K a 35K ... el modelo va a empezar a desviarse ... decayendo su performance.

In [19]:
df['ubigeo_buro'].unique()
#Esto no soporta la aparición de nuevas categorias - MONITOREAR LA APARICIÓN DE NUEVAS CATEGORIAS

array([ 3, 11,  4,  0,  2,  8,  9,  1,  6, 10,  5,  7])

In [20]:
df.grp_camptot06m = df.grp_camptot06m.fillna('Otro')

In [21]:
df.grp_campecs06m= df.grp_campecs06m.fillna('Otro')

In [22]:
df.region= df.region.fillna('Otro')

In [23]:
df.grp_riesgociiu= df.grp_riesgociiu.fillna('Otro')

In [24]:
features_encoder = ['grp_camptottlv06m','grp_campecstlv06m','grp_camptot06m','grp_campecs06m','region', 'grp_riesgociiu', 'ubigeo_buro']
for columna in features_encoder:
  print(columna)
  ds_clase = LabelEncoder()
  ds_clase.fit(df[columna]) # entrenando
  df[columna] = ds_clase.transform(df[columna]) # inferencia

grp_camptottlv06m
grp_campecstlv06m
grp_camptot06m
grp_campecs06m
region
grp_riesgociiu
ubigeo_buro

In [25]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
p_codmes,77884.0,201910.578964,1.105269,201909.0,201910.0,201911.0,201912.00000,2.019120e+05
target,79086.0,0.037883,0.190914,0.0,0.0,0.0,0.00000,1.000000e+00
monto,77884.0,23110.271686,15716.874469,100.0,11900.0,19600.0,30000.00000,1.500000e+05
ctd_prod_rccsf_m01,79086.0,4.083175,1.841823,0.0,3.0,4.0,5.00000,1.200000e+01
prom_salvig_entprinc_pp_rccsf_03m,79086.0,6895.058693,20345.406039,0.0,0.0,0.0,4536.32925,6.922512e+05
...,...,...,...,...,...,...,...,...
prm_saltotrdpj03m,79086.0,377.657505,4193.971583,0.0,0.0,0.0,0.00000,4.930500e+05
prm_saltotrdpj12m,79086.0,765.682442,9892.370319,0.0,0.0,0.0,0.00000,1.275240e+06
dsv_diasatrrdpj12m,79086.0,0.012343,0.327749,0.0,0.0,0.0,0.00000,3.539686e+01
max_pctsalimpago12m,79086.0,0.032584,0.144843,0.0,0.0,0.0,0.00000,1.000000e+00
prm_diasatrrdpj03m,79086.0,0.003412,0.158684,0.0,0.0,0.0,0.00000,2.266700e+01

# ASIGNACIÓN DE TIPO DE DATOS

Parte del principio de reproductibilidad

In [26]:
df.monto=df.monto.astype( 'float64')
df.target=df.target.astype('int32')
df.ctd_prod_rccsf_m01=df.ctd_prod_rccsf_m01.astype( 'int32')
df.prom_salvig_entprinc_pp_rccsf_03m=df.prom_salvig_entprinc_pp_rccsf_03m.astype( 'float64')
df.max_usotcrrstsf06m=df.max_usotcrrstsf06m.astype( 'float64')
df.max_usotcrrstsf03m=df.max_usotcrrstsf03m.astype( 'float64')
df.prm_lintcribksf06m=df.prm_lintcribksf06m.astype( 'float64')
df.lin_tcribksf03m=df.lin_tcribksf03m.astype( 'float64')
df.lin_tcribksf06m=df.lin_tcribksf06m.astype( 'float64')
df.cre_salvig_pp_rccsf_m02=df.cre_salvig_pp_rccsf_m02.astype( 'float64')
df.prm_usotcrrstsf06m=df.prm_usotcrrstsf06m.astype( 'float64')
df.prm_lintcribksf03m=df.prm_lintcribksf03m.astype( 'float64')
df.prm_usotcrrstsf03m=df.prm_usotcrrstsf03m.astype( 'float64')
df.ratuso_tcrrstsf_m13=df.ratuso_tcrrstsf_m13.astype( 'float64')
df.promctdprodrccsf3m=df.promctdprodrccsf3m.astype( 'float64')
df.ratpct_saldopprcc_m13=df.ratpct_saldopprcc_m13.astype( 'float64')
df.promctdprodrccsf6m=df.promctdprodrccsf6m.astype( 'float64')
df.ctd_actrccsf_6m=df.ctd_actrccsf_6m.astype( 'int32')
df.ctd_flgact_rccsf_m01=df.ctd_flgact_rccsf_m01.astype( 'int32')
df.sld_ep1ppeallsfm01=df.sld_ep1ppeallsfm01.astype( 'float64')
df.prm_sldvigrstsf12m=df.prm_sldvigrstsf12m.astype( 'float64')
df.sldtot_tcrsrcf=df.sldtot_tcrsrcf.astype( 'float64')
df.sldvig_tcrsrcf=df.sldvig_tcrsrcf.astype( 'float64')
df.flg_lintcrripsaga=df.flg_lintcrripsaga.astype( 'int32')
df.flg_svtcrsrcf=df.flg_svtcrsrcf.astype( 'int32')
df.flg_sdtcrripsaga=df.flg_sdtcrripsaga.astype( 'int32')
df.flg_sttcrsrcf=df.flg_sttcrsrcf.astype( 'int32')
df.flg_svltcrsrcf=df.flg_svltcrsrcf.astype( 'int32')
df.max_camptottlv06m=df.max_camptottlv06m.astype( 'int32')
df.min_camptottlv06m=df.min_camptottlv06m.astype( 'int32')
df.frc_camptottlv06m=df.frc_camptottlv06m.astype( 'int32')
df.rec_camptottlv06m=df.rec_camptottlv06m.astype( 'int32')
df.grp_camptottlv06m=df.grp_camptottlv06m.astype( 'int32')
df.ctd_camptottlv06m=df.ctd_camptottlv06m.astype( 'int32')
df.prm_camptottlv06m=df.prm_camptottlv06m.astype( 'float64')
df.max_campecstlv06m=df.max_campecstlv06m.astype( 'int32')
df.min_campecstlv06m=df.min_campecstlv06m.astype( 'int32')
df.frc_campecstlv06m=df.frc_campecstlv06m.astype( 'int32')
df.rec_campecstlv06m=df.rec_campecstlv06m.astype( 'int32')
df.grp_campecstlv06m=df.grp_campecstlv06m.astype( 'int32')
df.ctd_campecstlv06m=df.ctd_campecstlv06m.astype( 'int32')
df.prm_campecstlv06m=df.prm_campecstlv06m.astype( 'float64')
df.max_camptot06m=df.max_camptot06m.astype( 'int32')
df.min_camptot06m=df.min_camptot06m.astype( 'int32')
df.frc_camptot06m=df.frc_camptot06m.astype( 'int32')
df.rec_camptot06m=df.rec_camptot06m.astype( 'int32')
df.grp_camptot06m=df.grp_camptot06m.astype( 'int32')
df.ctd_camptot06m=df.ctd_camptot06m.astype( 'int32')
df.prm_camptot06m=df.prm_camptot06m.astype( 'float64')
df.max_campecs06m=df.max_campecs06m.astype( 'int32')
df.min_campecs06m=df.min_campecs06m.astype( 'int32')
df.frc_campecs06m=df.frc_campecs06m.astype( 'int32')
df.rec_campecs06m=df.rec_campecs06m.astype( 'int32')
df.grp_campecs06m=df.grp_campecs06m.astype( 'int32')
df.ctd_campecs06m=df.ctd_campecs06m.astype( 'int32')
df.prm_campecs06m=df.prm_campecs06m.astype( 'float64')
# ... definir tipos de datos para cada variable

In [27]:
def fun_conv(df, columns, type):
  for c in columns:
    df[c] = df[c].astype(type)

columns_int32 = ['rec_campecs06m', 'grp_campecs06m', 'ctd_campecs06m']
columns_float64 = ['prm_campecstlv06m', 'prm_campecs06m']

In [28]:
fun_conv(df, columns_int32, 'int32')

In [29]:
df

,p_codmes,key_value,target,monto,ctd_prod_rccsf_m01,prom_salvig_entprinc_pp_rccsf_03m,max_usotcrrstsf06m,max_usotcrrstsf03m,prm_lintcribksf06m,lin_tcribksf03m,...,beta_saltotppe12m,prm_entrd03m,ctd_entrdm01,beta_saltotppe06m,prm_diasatrrd03m,prm_saltotrdpj03m,prm_saltotrdpj12m,dsv_diasatrrdpj12m,max_pctsalimpago12m,prm_diasatrrdpj03m
0,201912.0,2A7AA560ED5426EEBCBA5678510D53FDE5C30E3E309BC1...,0,15000.0,6,0.000,0.015,0.015,9400.000,28200.00,...,0.000,1.667,2.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0
1,201912.0,7581203BF579C305ED0A62F8374CACD0925F7BA1C70DD2...,0,44800.0,1,0.000,0.000,0.000,10000.000,30000.00,...,0.000,1.333,1.0,0.000,0.0,57500.0,60500.000,0.0,0.000,0.0
2,201912.0,3B9C6C94C9274C64DFC7FE325931589B1C2B5B229600A1...,0,12200.0,7,3515.793,0.223,0.194,18500.000,55500.00,...,-67.669,4.667,5.0,-80.264,0.0,0.0,0.000,0.0,0.000,0.0
3,201912.0,8C9FB47C7499B7C65224D77D1BBB1C78F3AA2F4920EBF0...,0,21300.0,2,0.000,0.831,0.481,4900.000,14700.00,...,0.000,2.000,2.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0
4,201912.0,4A68666AF9B98056E7B257CB44957A92EA587DAC9DB1A7...,0,36000.0,2,0.000,0.809,0.809,9000.000,27000.00,...,0.000,2.000,2.0,0.000,0.0,0.0,131.075,0.0,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79081,201911.0,A4E5482EFEF2807DDB7813E9528498FCF5F6B81B7C6D09...,0,10200.0,4,0.000,0.524,0.490,20475.685,57574.37,...,-95.630,3.667,3.0,0.000,0.0,0.0,0.000,0.0,0.049,0.0
79082,201911.0,D6E4A8D42587BEBF504FCB8E79EA254BB9BE96619D5CED...,0,12800.0,6,5494.263,0.487,0.020,6116.667,19000.00,...,-423.127,3.667,3.0,-1297.086,0.0,0.0,0.000,0.0,0.023,0.0
79083,201911.0,5B03358580A8D6ADA03582E7D97D50F62C674C0090F383...,0,9600.0,6,10783.380,0.401,0.401,9000.000,27000.00,...,-1975.294,5.333,5.0,-779.508,0.0,0.0,0.000,0.0,0.000,0.0
79084,201911.0,322A9C737747747C0AB31D867299634FF28FC92BBA0EA3...,0,30000.0,3,0.000,0.039,0.039,60000.000,180000.00,...,0.000,2.667,2.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0
79085,201911.0,DB31BF387A776822E1F98913FF6AD80CB64DD112FD2460...,0,30000.0,8,2111.580,0.076,0.072,81883.957,251083.12,...,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.0,0.000,0.0

# DATA SPLIT

In [30]:
df_val = df[df['p_codmes'] == 201912.0]
df_val

,p_codmes,key_value,target,monto,ctd_prod_rccsf_m01,prom_salvig_entprinc_pp_rccsf_03m,max_usotcrrstsf06m,max_usotcrrstsf03m,prm_lintcribksf06m,lin_tcribksf03m,...,beta_saltotppe12m,prm_entrd03m,ctd_entrdm01,beta_saltotppe06m,prm_diasatrrd03m,prm_saltotrdpj03m,prm_saltotrdpj12m,dsv_diasatrrdpj12m,max_pctsalimpago12m,prm_diasatrrdpj03m
0,201912.0,2A7AA560ED5426EEBCBA5678510D53FDE5C30E3E309BC1...,0,15000.0,6,0.000,0.015,0.015,9400.000,28200.00,...,0.000,1.667,2.0,0.000,0.0,0.0,0.000,0.0,0.00,0.0
1,201912.0,7581203BF579C305ED0A62F8374CACD0925F7BA1C70DD2...,0,44800.0,1,0.000,0.000,0.000,10000.000,30000.00,...,0.000,1.333,1.0,0.000,0.0,57500.0,60500.000,0.0,0.00,0.0
2,201912.0,3B9C6C94C9274C64DFC7FE325931589B1C2B5B229600A1...,0,12200.0,7,3515.793,0.223,0.194,18500.000,55500.00,...,-67.669,4.667,5.0,-80.264,0.0,0.0,0.000,0.0,0.00,0.0
3,201912.0,8C9FB47C7499B7C65224D77D1BBB1C78F3AA2F4920EBF0...,0,21300.0,2,0.000,0.831,0.481,4900.000,14700.00,...,0.000,2.000,2.0,0.000,0.0,0.0,0.000,0.0,0.00,0.0
4,201912.0,4A68666AF9B98056E7B257CB44957A92EA587DAC9DB1A7...,0,36000.0,2,0.000,0.809,0.809,9000.000,27000.00,...,0.000,2.000,2.0,0.000,0.0,0.0,131.075,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79057,201912.0,CAE54992E5E4F53C644256C74C64238B83F8739FFC112F...,0,41400.0,1,0.000,0.000,0.000,48418.580,134700.00,...,0.000,1.000,1.0,0.000,0.0,0.0,0.000,0.0,0.00,0.0
79058,201912.0,574179E0AEFE42174BE168168D1B9876A51559BF4F5457...,0,93500.0,7,37003.280,0.096,0.096,46900.000,140700.00,...,2400.448,5.333,5.0,-21231.102,32.0,0.0,0.000,0.0,0.02,0.0
79059,201912.0,CD0A1E1115CB00ACFC5AD81656A778A0B4ECCDE3CF3085...,0,12500.0,2,0.000,0.338,0.229,1700.000,5100.00,...,0.000,1.000,1.0,0.000,0.0,0.0,0.000,0.0,0.00,0.0
79060,201912.0,1CCF26B93FC2211E895F1FD80D98E9989BBD3262B283C8...,0,25200.0,2,0.000,0.000,0.000,6808.882,19647.27,...,-957.214,1.000,1.0,-544.287,0.0,0.0,0.000,0.0,0.00,0.0
79061,201912.0,0D814B31E64AC0DA8497564EACEA8A8713D633124FD730...,0,10600.0,1,0.000,0.000,0.000,15000.000,45000.00,...,0.000,1.000,1.0,0.000,0.0,0.0,0.000,0.0,0.00,0.0

In [31]:
from sklearn.model_selection import train_test_split
df_main = df[~(df.p_codmes == 201912.0)]
df_train, df_test = train_test_split(df_main, test_size=0.30, random_state = 123)

In [32]:
df_train

,p_codmes,key_value,target,monto,ctd_prod_rccsf_m01,prom_salvig_entprinc_pp_rccsf_03m,max_usotcrrstsf06m,max_usotcrrstsf03m,prm_lintcribksf06m,lin_tcribksf03m,...,beta_saltotppe12m,prm_entrd03m,ctd_entrdm01,beta_saltotppe06m,prm_diasatrrd03m,prm_saltotrdpj03m,prm_saltotrdpj12m,dsv_diasatrrdpj12m,max_pctsalimpago12m,prm_diasatrrdpj03m
49025,201911.0,D9A704CFE8A44AE4DE922D39E2CB584836793290518BC8...,0,6000.0,2,0.000,0.259,0.259,1000.000,3000.00,...,0.000,0.667,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
5719,201911.0,75B411883FAF523C8BFB51942E20093F0990FBC9360B66...,0,28500.0,3,0.000,0.091,0.031,94390.248,267125.46,...,0.000,2.667,3.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
67912,201909.0,D570FC7AE61B047BD88FA11ED132838F92D4E86FB5A9E9...,0,14800.0,2,0.000,0.010,0.000,9470.002,32520.01,...,-221.594,2.000,2.0,-221.594,0.0,0.0,0.0,0.0,0.0,0.0
8237,201909.0,46AAA198E2EBCF9210954FDECE1B859BF57F2B910F5670...,0,11300.0,7,0.000,0.004,0.000,8100.000,24300.00,...,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
75528,201911.0,9D0E0F9D072B5DF8D16F406523222132ECB9CD4EB6FD0E...,0,30000.0,5,43204.033,0.601,0.153,54200.000,162600.00,...,-3904.414,2.333,3.0,-3904.414,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75244,201910.0,904C647CFD1184524FE544E1F921096C074FE149631EEF...,0,31800.0,5,0.000,0.226,0.226,27100.000,81300.00,...,0.000,1.667,2.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
25236,201911.0,AF933B1F186F33C60BF6783729410463D38D7C213944D2...,0,28700.0,3,0.000,0.014,0.014,34800.000,104400.00,...,0.000,1.667,1.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
39637,201909.0,BE45B0047C115C9E8B1E01252A934A73AEEE0F539F4347...,0,21100.0,7,14382.857,0.590,0.588,34500.000,103500.00,...,-960.022,4.333,5.0,-982.671,0.0,0.0,0.0,0.0,0.0,0.0
22276,201911.0,89B79C12695825B3BF4C58C7476A5592911F9461A50ADF...,0,28800.0,5,0.000,0.335,0.335,22623.727,91042.36,...,0.000,3.000,3.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0
73310,201911.0,7C9CB40EC5C977A38737A36EBF9BCAF3D0F4FBF101EA92...,1,46200.0,4,0.000,0.648,0.625,59900.995,186290.50,...,0.000,4.000,4.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
df_test

,p_codmes,key_value,target,monto,ctd_prod_rccsf_m01,prom_salvig_entprinc_pp_rccsf_03m,max_usotcrrstsf06m,max_usotcrrstsf03m,prm_lintcribksf06m,lin_tcribksf03m,...,beta_saltotppe12m,prm_entrd03m,ctd_entrdm01,beta_saltotppe06m,prm_diasatrrd03m,prm_saltotrdpj03m,prm_saltotrdpj12m,dsv_diasatrrdpj12m,max_pctsalimpago12m,prm_diasatrrdpj03m
47825,201909.0,F9B04E1667FFDC3D879610710BFB7A44A49D0B21C4CD10...,0,10400.0,2,0.000,0.479,0.372,2700.000,2700.00,...,0.000,2.333,3.0,0.000,0.0,4119.403,3496.697,0.0,0.000,0.0
66867,201910.0,52F3C162EB53E2C81B9BE7177F6B5EAAD032E7C61D17F2...,0,30000.0,6,216559.327,0.347,0.347,65800.000,197400.00,...,2044.446,2.333,2.0,-1515.201,0.0,0.000,0.000,0.0,0.000,0.0
8177,201909.0,773DBA09FCEEFA7860CF4D5CA0D377E74685F3BBDBCEE5...,0,12200.0,3,29970.630,0.000,0.000,5500.000,16500.00,...,-341.310,1.000,1.0,-370.620,0.0,0.000,0.000,0.0,1.000,0.0
24557,201910.0,E07B2DC49B223A6A96B4EAD29894D64E57E70256DBBEBF...,0,3600.0,4,0.000,0.505,0.505,6766.667,21900.00,...,0.000,2.333,2.0,0.000,0.0,0.000,0.000,0.0,0.000,0.0
57621,201910.0,C1DE8AD74A8DE8B29D44156AEC7271DC5101F758D09346...,0,30000.0,2,0.000,0.000,0.000,19538.288,87829.73,...,0.000,2.000,2.0,0.000,0.0,0.000,2399.140,0.0,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24897,201910.0,9C1777D22508BEF9E89F2070FBAD9BA855BA16ED782227...,0,26300.0,6,0.000,0.738,0.738,4200.000,12600.00,...,0.000,5.333,5.0,0.000,0.0,0.000,0.000,0.0,0.097,0.0
24232,201910.0,15BF1ADE559AF1DA19F7B85A081DAA7F9BD47EC650B769...,0,36200.0,4,0.000,0.457,0.457,38913.557,113193.95,...,0.000,4.000,4.0,0.000,0.0,0.000,0.000,0.0,0.000,0.0
31203,201911.0,2A490BE9411C002D67EBFE7DD8E389CDF139EF22585D27...,0,21900.0,2,0.000,0.982,0.935,7716.667,34600.00,...,0.000,2.000,2.0,0.000,0.0,0.000,0.000,0.0,0.000,0.0
66945,201909.0,708FF90330B826BAC6886D0088EFE67E005CDF28D3BAC5...,0,10300.0,8,4674.903,0.076,0.076,5600.000,11200.00,...,-92.273,3.667,6.0,482.236,0.0,0.000,0.000,0.0,0.000,0.0
19527,201909.0,10F52DD964A48AE9962C1C505307D35C06A933CF8F55ED...,0,15000.0,7,5000.000,0.072,0.057,15000.000,15000.00,...,193.435,5.000,6.0,0.000,0.0,0.000,0.000,0.0,0.000,0.0

# **Entrenamiento**

In [54]:
x_train = df_train.iloc[:, 3::]
y_train = df_train.iloc[:, 2]

x_test = df_test.iloc[:, 3::]
y_test = df_test.iloc[:, 2]

x_val = df_val.iloc[:, 3::]
y_val = df_val.iloc[:, 2]

In [55]:
import xgboost as xgb

model = xgb.XGBClassifier(eval_metrics = 'logloss', use_label_encoder = False) #toy model
model.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:183: UserWarning: [21:30:54] WARNING: /workspace/src/learner.cc:738:
Parameters: { "eval_metrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None,
              eval_metrics='logloss', feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, ...)

# **Drift de scores**

Vamos a medir la estabilidad de los scores puros

In [56]:
y_test_pred = model.predict_proba(x_test)[:, 1]
y_val_pred = model.predict_proba(x_val)[:, 1]

***Ejercicio***

''y_val_pred'' es el dataframe actual, y el ''y_test_pred'' es la muestra de referencia. Medir el PSI y el KL.

In [68]:
import pandas as pd
import numpy as np

def calculate_psi(expected_array, actual_array, buckets):#buckets o quantiles
    breakpoints = np.percentile(expected_array, np.linspace(0, 100, buckets + 1))
    breakpoints[0] = -np.inf  # para incluir todos los valores
    breakpoints[-1] = np.inf

    expected_counts = np.histogram(expected_array, bins=breakpoints)[0] / len(expected_array)
    actual_counts = np.histogram(actual_array, bins=breakpoints)[0] / len(actual_array)

    # Evita divisiones por cero o log(0)
    expected_counts = np.where(expected_counts == 0, 1e-6, expected_counts)
    actual_counts = np.where(actual_counts == 0, 1e-6, actual_counts)

    # calculo del PSI
    psi_values = (expected_counts - actual_counts) * np.log(expected_counts / actual_counts)
    return np.sum(psi_values)

def calculate_kl(expected_array, actual_array, buckets):#buckets o quantiles
    breakpoints = np.percentile(expected_array, np.linspace(0, 100, buckets + 1))
    breakpoints[0] = -np.inf  # para incluir todos los valores
    breakpoints[-1] = np.inf

    expected_counts = np.histogram(expected_array, bins=breakpoints)[0] / len(expected_array)
    actual_counts = np.histogram(actual_array, bins=breakpoints)[0] / len(actual_array)

    # Evita divisiones por cero o log(0)
    expected_counts = np.where(expected_counts == 0, 1e-6, expected_counts)
    actual_counts = np.where(actual_counts == 0, 1e-6, actual_counts)

    # calculo del KL
    kl_div_values = expected_counts * np.log(expected_counts / actual_counts) #expected_counts: referencia
    return np.sum(kl_div_values)

def drift_metrics(actual_array, expected_array, quantils): #dataframe actual, dataframe referencia, particiones
  results = []
  if pd.api.types.is_numeric_dtype(actual_array) and pd.api.types.is_numeric_dtype(expected_array):
      kl_value = calculate_kl(expected_array, actual_array, quantils)
      psi_value = calculate_psi(expected_array, actual_array, quantils)

      results.append({'PSI': psi_value,
                      'KL_div': kl_value})

  return pd.DataFrame(results)

In [69]:
drift_metrics(y_val_pred, y_test_pred, 100)

        PSI    KL_div
0  0.053308  0.029373

# **Medición del performance**

In [70]:
from sklearn.metrics import roc_auc_score, roc_curve

def medir_auc(y_true, y_pred):
  fpr, tpr, thresholds = roc_curve(y_true, y_pred)
  return roc_auc_score(y_true, y_pred)

In [73]:
y_train_pred = model.predict_proba(x_train)[:, 1]
y_test_pred = model.predict_proba(x_test)[:, 1]
y_val_pred = model.predict_proba(x_val)[:, 1]

print(medir_auc(y_train, y_train_pred))
print(medir_auc(y_test, y_test_pred))
# train y test comparten meses - siguen la misma distribución
print(medir_auc(y_val, y_val_pred))
# validation está fuera de la distribución anterior (meses nuevos).

0.9932843586703006
0.7055956965531117
0.7211380301018525